import { Schema, model } from 'mongoose';
import { IEnrollment } from './interface';

const enrollmentSchema = new Schema<IEnrollment>(
  {
    student: { type: Schema.Types.ObjectId, ref: 'Student' },
    studentPhoto: { type: String },
    studentId: { type: String },
    mobileNo: { type: String },
    rollNumber: { type: String },
    studentName: { type: String },
    nameBangla: { type: String },
    gender: { type: String },
    birthDate: { type: String },
    birthRegistrationNo: { type: String },
    bloodGroup: { type: String },
    nationality: { type: String, default: 'Bangladesh' },
    className: [{ type: Schema.Types.ObjectId, ref: 'Class' }],
    section: { type: String },
    roll: { type: String },
    session: { type: String },
    batch: { type: String },
    studentType: { type: String },
    fees: [{ type: Schema.Types.ObjectId, ref: 'Fees' }],
    paymentStatus: { type: String, default: 'pending' },

    parentInfo: {
      father: {
        nameBangla: { type: String },
        nameEnglish: { type: String },
        profession: { type: String },
        education: { type: String },
        mobile: { type: String },
        whatsapp: { type: String },
        nid: { type: String },
        income: { type: Number },
      },
      mother: {
        nameBangla: { type: String },
        nameEnglish: { type: String },
        profession: { type: String },
        education: { type: String },
        mobile: { type: String },
        whatsapp: { type: String },
        nid: { type: String },
        income: { type: Number },
      },
      guardian: {
        nameBangla: { type: String },
        nameEnglish: { type: String },
        relation: { type: String },
        mobile: { type: String },
        whatsapp: { type: String },
        profession: { type: String },
        address: { type: String },
      },
    },

    studentDepartment: { type: String },
    presentAddress: {
      village: { type: String },
      postOffice: { type: String },
      postCode: { type: String },
      policeStation: { type: String },
      district: { type: String },
    },
    permanentAddress: {
      village: { type: String },
      postOffice: { type: String },
      postCode: { type: String },
      policeStation: { type: String },
      district: { type: String },
    },
    documents: {
      birthCertificate: { type: Boolean, default: false },
      transferCertificate: { type: Boolean, default: false },
      characterCertificate: { type: Boolean, default: false },
      markSheet: { type: Boolean, default: false },
      photographs: { type: Boolean, default: false },
    },
    familyEnvironment: {
      halalIncome: { type: String },
      parentsPrayer: { type: String },
      addiction: { type: String },
      tv: { type: String },
      quranRecitation: { type: String },
      purdah: { type: String },
    },
    behaviorSkills: {
      mobileUsage: { type: String },
      generalBehavior: { type: String },
      obedience: { type: String },
      elderBehavior: { type: String },
      youngerBehavior: { type: String },
      lyingStubbornness: { type: String },
      studyInterest: { type: String },
      religiousInterest: { type: String },
      angerControl: { type: String },
    },
    previousSchool: {
      institution: { type: String },
      address: { type: String },
    },
    termsAccepted: { type: Boolean, default: false },
    promotedFrom: { type: Schema.Types.ObjectId, ref: 'Enrollment' },
    promotedTo: { type: Schema.Types.ObjectId, ref: 'Enrollment' },
    admissionType: {
      type: String,
      enum: ['admission', 'promotion'],
      default: 'admission',
    },
    status: {
      type: String,
      enum: ['active', 'passed', 'failed', 'left'],
      default: 'active',
    },
    totalAmount: { type: Number, default: 0 },
    paidAmount: { type: Number, default: 0 },
    dueAmount: { type: Number, default: 0 },
    totalDiscount: { type: Number, default: 0 },
    advanceBalance: { type: Number, default: 0 },
  },
  { timestamps: true },
);

export const Enrollment = model<IEnrollment>('Enrollment', enrollmentSchema);
